## Numpy 数组 
- 基础
 - 导入
 - 创建
 - 查询数组类型
 - 数组计算（加减乘除）
 - 查询特性
 - 数组转换
 - 数组复制
- 切片和索引
 - 数值查询
 - bool查询
- 数值运算
 - 加
 - 乘
 - 统计
 - 矩阵乘法
- 功能模块
 - 排序操作
 - 形状操作
 - 数组拼接
 - 数组函数
 - 随机模块
 - 文件写入

### 1 基础 

In [197]:
#导入
import numpy as np

In [198]:
#创建
print("-----创建-----")
array = np.array([1,2,3,4,5])
array_float = np.array([1,2,3,4,5], dtype=np.float32)
array_str = np.array([1,2,3,4,5], dtype=object)
print(array)
print(array_float)
print(array_str)

-----创建-----
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1 2 3 4 5]


In [199]:
#查询数组类型
print("-----查询数组类型-----")
print(type(array))

-----查询数组类型-----
<class 'numpy.ndarray'>


In [200]:
#数组计算(加减乘除)
print("-----数组计算(加减乘除)-----")
array2 = array + 1
array3 = array + array2
array4 = array - 1
array5 = array - array2
array6 = array * array2
array7 = np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8],[5,6,7,8,9]])
array8 = array7 * array
array9 = np.array([[1],[2],[3],[4],[5]])
array10 = array9 * array
print(array2)
print(array3)
print(array4)
print(array5)
print(array6)
print(array7)
print(array8)
print(array9)
print(array10) # 注意乘法规律

-----数组计算(加减乘除)-----
[2 3 4 5 6]
[ 3  5  7  9 11]
[0 1 2 3 4]
[-1 -1 -1 -1 -1]
[ 2  6 12 20 30]
[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]
[[ 1  4  9 16 25]
 [ 2  6 12 20 30]
 [ 3  8 15 24 35]
 [ 4 10 18 28 40]
 [ 5 12 21 32 45]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [201]:
#查询特性
print("-----查询特性-----")
print(array.shape)
print(array2.shape)
print(array3.shape)
print(array4.shape)
print(array5.shape)
print(array6.shape)
print(array7.shape)
print(array8.shape)
print(array9.shape)
print(array10.shape)
array11 = np.array([1,2,3,4,'5'])
print(array11) # 注意会向下兼容 int-float-str
print(array.dtype)
print(array_float.dtype)
print(array_str.dtype)
print(array.size)
print(array.ndim)

-----查询特性-----
(5,)
(5,)
(5,)
(5,)
(5,)
(5,)
(5, 5)
(5, 5)
(5, 1)
(5, 5)
['1' '2' '3' '4' '5']
int64
float32
object
5
1


In [202]:
#数组转换
print("-----数组转换-----")
array_float2 = np.asarray(array, dtype = np.float32)
print(array_float2)
array_str2 = np.asarray(array, dtype = object)
print(array_str2)

-----数组转换-----
[1. 2. 3. 4. 5.]
[1 2 3 4 5]


In [203]:
#数组复制
print("-----数组复制-----")
array_origin = np.array([[1,2,3,4,5]])
array_new = array_origin
array_new[0,0] = 100
print(array_origin)
print(array_new)

array_origin2 = np.array([[1,2,3,4,5]])
array_new2 = array_origin2.copy()
array_new2[0,0] = 100
print(array_origin2)
print(array_new2)

-----数组复制-----
[[100   2   3   4   5]]
[[100   2   3   4   5]]
[[1 2 3 4 5]]
[[100   2   3   4   5]]


### 2 切片和索引 

In [204]:
# 数值查询
print("-----数值查询-----")
tang_array = np.array([1,2,3,4,5])
print(tang_array[1:3]) # 左闭右开
print(tang_array[-3:]) 
tang_array2 = np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8],[5,6,7,8,9]])
tang_array2[1,1] = 10
print(tang_array2)
print(tang_array2[1]) # 取第二行
print(tang_array2[:,2]) # 取第三列
print(tang_array2[1:3, 2:4]) # 取特定行列，左闭右开

# bool查询
print("-----bool查询-----")
bool_array = np.arange(0,100,10)
mask = np.array([0,0,1,0,0,1,0,0,1,1], dtype = bool) # 方法一
print(bool_array[mask]) 
mask2 = bool_array > 50  # 方法二
print(bool_array[mask2])
mask3 = np.where(bool_array<50)  # 方法三
print(bool_array[mask3])
x = np.array([1,2,3,4,5])
y = np.array([5,4,3,2,1])
print(x==y)
print(np.logical_and(x,y))
print(np.logical_or(x,y))


-----数值查询-----
[2 3]
[3 4 5]
[[ 1  2  3  4  5]
 [ 2 10  4  5  6]
 [ 3  4  5  6  7]
 [ 4  5  6  7  8]
 [ 5  6  7  8  9]]
[ 2 10  4  5  6]
[3 4 5 6 7]
[[4 5]
 [5 6]]
-----bool查询-----
[20 50 80 90]
[60 70 80 90]
[ 0 10 20 30 40]
[False False  True False False]
[ True  True  True  True  True]
[ True  True  True  True  True]


### 3 数值运算 

In [205]:
print("-----数值运算-----")
print("-----加-----")
tang_array = np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8],[5,6,7,8,9],[6,7,8,9,10]])
print(np.sum(tang_array))
print(np.sum(tang_array, axis=0))
print(np.sum(tang_array, axis=1))

-----数值运算-----
-----加-----
165
[21 27 33 39 45]
[15 20 25 30 35 40]


In [206]:
print("-----乘-----")
print(tang_array.prod())
print(tang_array.prod(axis=0))
print(tang_array.prod(axis=1))

-----乘-----
4903375104664141824
[   720   5040  20160  60480 151200]
[  120   720  2520  6720 15120 30240]


In [207]:
print("-----统计-----")
print(tang_array.min())
print(tang_array.min(axis=0))
print(tang_array.min(axis=1))
print(tang_array.max())
print(tang_array.max(axis=0))
print(tang_array.max(axis=1))
print(tang_array.mean())
print(tang_array.mean(axis=0))
print(tang_array.mean(axis=1))
print(tang_array.std())
print(tang_array.std(axis=0))
print(tang_array.std(axis=1))
print(tang_array.var())
print(tang_array.var(axis=0))
print(tang_array.var(axis=1))
print(tang_array.var(axis=0).round())
print(tang_array.var(axis=0).round(decimals=1))
print(tang_array.var(axis=0).round(decimals=2))

-----统计-----
1
[1 2 3 4 5]
[1 2 3 4 5 6]
10
[ 6  7  8  9 10]
[ 5  6  7  8  9 10]
5.5
[3.5 4.5 5.5 6.5 7.5]
[3. 4. 5. 6. 7. 8.]
2.217355782608345
[1.71 1.71 1.71 1.71 1.71]
[1.41 1.41 1.41 1.41 1.41 1.41]
4.916666666666667
[2.92 2.92 2.92 2.92 2.92]
[2. 2. 2. 2. 2. 2.]
[3. 3. 3. 3. 3.]
[2.9 2.9 2.9 2.9 2.9]
[2.92 2.92 2.92 2.92 2.92]


In [208]:
print("-----矩阵乘法-----")
x = np.array([1,2])
y = np.array([4,8])
z = np.multiply(x,y) #交叉相乘
print(x)
print(y)
print(z)
z1 = np.dot(x,y) #矩阵乘法
print(z1) 

y1 = np.array([[4],[8]])
x.shape = 2,1
y1.shape = 1,2
print(x)
print(y1)
z2 = np.dot(x,y1) #矩阵乘法
print(z2)

y2 = np.array([[4],[8]])
x.shape = 2,1
y2.shape = 1,2
print(x)
print(y2)
z3 = np.dot(y2,x) #矩阵乘法
print(z3) 

-----矩阵乘法-----
[1 2]
[4 8]
[ 4 16]
20
[[1]
 [2]]
[[4 8]]
[[ 4  8]
 [ 8 16]]
[[1]
 [2]]
[[4 8]]
[[20]]


### 4 功能模块 

In [209]:
#排序操作
print("-----排序操作-----")
sort_array = np.array([[1.5, 2.3, 6.7],[3.4, 9.10, 2.4]])
sort_a = np.sort(sort_array) #行排序
sort_array = np.array([[1.5, 2.3, 6.7],[3.4, 9.10, 2.4]])
sort_b = np.sort(sort_array, axis=0) #列排序
sort_array = np.array([[1.5, 2.3, 6.7],[3.4, 9.10, 2.4]])
sort_c = np.sort(sort_array, axis=1) #行排序
print(sort_array)
print(sort_a)
print(sort_b)
print(sort_c)

print("-----排序索引-----")
sort_array = np.array([[1.5, 2.3, 6.7],[3.4, 9.10, 2.4]])
sort_index = np.argsort(sort_array)  #原始索引的位置
print(sort_array)
print(sort_index)

print("-----寻找排序-----")
join_array = np.linspace(0,10,10)
values = np.array([2.5,5.5,8.5])
where_index = np.searchsorted(join_array, values)  #原始索引的位置
print(join_array)
print(where_index)

print("-----指示排序-----")
guide_array = np.array([[1,0,6],[1,7,0],[2,3,1],[2,4,0]])
index = np.lexsort([-1*guide_array[:,0]]) #按照第一列的降序排列
new_array = guide_array[index] 
print(index)
print(new_array)

-----排序操作-----
[[1.5 2.3 6.7]
 [3.4 9.1 2.4]]
[[1.5 2.3 6.7]
 [2.4 3.4 9.1]]
[[1.5 2.3 2.4]
 [3.4 9.1 6.7]]
[[1.5 2.3 6.7]
 [2.4 3.4 9.1]]
-----排序索引-----
[[1.5 2.3 6.7]
 [3.4 9.1 2.4]]
[[0 1 2]
 [2 0 1]]
-----寻找排序-----
[ 0.    1.11  2.22  3.33  4.44  5.56  6.67  7.78  8.89 10.  ]
[3 5 8]
-----指示排序-----
[2 3 0 1]
[[2 3 1]
 [2 4 0]
 [1 0 6]
 [1 7 0]]


In [210]:
#形状操作
print("-----形状操作-----")
shape_array = np.arange(10)
print(shape_array)
print(shape_array.shape)
shape_array = np.arange(10)
shape_array.shape = 5,2
print(shape_array)
print(shape_array.shape)
shape_array = np.arange(10)
shape_array = shape_array[np.newaxis,:] #增加新列
print(shape_array)
shape_array = shape_array.squeeze() #删除空列
print(shape_array)
shape_array = shape_array[np.newaxis,:]
shape_array = shape_array.T #转秩 请注意 如果只用shape_array.T打印 则不改变原值
print(shape_array)

-----形状操作-----
[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)
[[0 1 2 3 4 5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [211]:
#数组拼接
print("-----数组拼接-----")
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
c = np.concatenate((a,b))
print(c)
c1 = np.concatenate((a,b), axis=0) #不变维度，纵向连接
print(c1)
c2 = np.concatenate((a,b), axis=1) #不变维度，横向连接
print(c2)
c3 = np.stack((a,b)) #新增维度
print(c3) 
c4 = np.hstack((a,b)) #不变维度，纵向连接
print(c4) 
c5 = np.vstack((a,b)) #不变维度，横向连接
print(c5) 
b1 = b.flatten() #拉平
print(b1) 

-----数组拼接-----
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 7  8  9 10 11 12]


In [212]:
#数组函数
print("-----数组函数-----")
z1 = np.arange(2,20,2)
z2 = np.logspace(0,1,5)
z3 = np.r_[0:5:1] #快速行
z4 = np.c_[0:5:1] #快速列
print(z1)
print(z2)
print(z3)
print(z4)

z5 = np.zeros(3)
z6 = np.zeros((3,3))
z7 = np.ones(3)
z8 = np.ones((3,3))
z9 = np.ones((3,3))*8
print(z5)
print(z6)
print(z7)
print(z8)
print(z9)

z10 = np.empty(6)
z11 = z10.fill(1) #先空再填充
print(z10)
print(z11)

exis_array = np.array([1,2,3,4,5,6])
z12 = np.zeros_like(exis_array) #适合在大规模数据中，初始化
print(z12)

z13 = np.identity(6) #仅对角线
print(z13)

-----数组函数-----
[ 2  4  6  8 10 12 14 16 18]
[ 1.    1.78  3.16  5.62 10.  ]
[0 1 2 3 4]
[[0]
 [1]
 [2]
 [3]
 [4]]
[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[8. 8. 8.]
 [8. 8. 8.]
 [8. 8. 8.]]
[1. 1. 1. 1. 1. 1.]
None
[0 0 0 0 0 0]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
#随机模块
print("-----随机模块-----")
r1 = np.random.rand()
r2 = np.random.rand(3,2)
r3 = np.random.randint(10,size=(3,2))
r4 = np.random.randint(0,10,3)
print(r1)
print(r2)
print(r3)
print(r4)

mu = 0
sigma = 1
r5 = np.random.normal(mu, sigma, 10) #均值为0 方差为1
print(r5)

np.set_printoptions(precision=2)
r6 = np.random.normal(mu, sigma, 10) #均值为0 方差为1
print(r6)

r7 = np.arange(10)
np.random.shuffle(r7) #原地操作 洗牌操作
print(r7)

np.random.seed(100)
r8 = np.random.normal(mu, sigma, 10) #均值为0 方差为1
print(r8)

In [192]:
%%writefile zuo.txt
1 2 3 4 5
2 3 4 5 6

data= np.loadtxt('zuo.txt')

Overwriting zuo.txt


In [193]:
%%writefile zuo2.txt
1,2,3,4,5
2,3,4,5,6

data2= np.loadtxt('zuo2.txt', delimiter=',')

Writing zuo2.txt


In [194]:
%%writefile zuo3.txt
x,y,z,a,b
1,2,3,4,5
2,3,4,5,6

data2= np.loadtxt('zuo3.txt', delimiter=',', skiprows=1)

Writing zuo3.txt


In [195]:
zuo_array = np.array([[1,2,3],[4,5,6]])
np.save('zuo_array.npy',zuo_array)
np.load('zuo_array.npy')

array([[1, 2, 3],
       [4, 5, 6]])